resources:
- frontend/
- backend/
- database/
- ingress/

images:
- name: team3capstoneacr.azurecr.io/express-server
  newTag: v2
- name: team3capstoneacr.azurecr.io/flask-api
  newTag: v1
- name: team3capstoneacr.azurecr.io/sqlite-db
  newTag: latest
- name: team3capstoneacr.azurecr.io/angular-app
  newTag: v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
