resources:
- frontend/
- backend/
- database/
- ingress/

configMapGenerator:
- literals:
  - ASPNETCORE_ENVIRONMENT=Development
  name: common-config

images:
- name: myacr121843.azurecr.io/optum-azure-capstone-express-server
  newTag: v4
- name: myacr121843.azurecr.io/optum-azure-capstone-flask-api
  newTag: v4
- name: myacr121843.azurecr.io/sqlite-db
  newTag: v4
- name: myacr121843.azurecr.io/optum-azure-capstone-angular-app
  newTag: v4
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
